title: 'Earth BitDevs'
tagline: 'Earth BitDevs is a global, online community for those interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'Events', url: '/events'}
  - {name: 'Contact', url: '#', external: true}
