title: 'Austin Bitcoin Developers'
tagline: 'Austin Bitcoin Developers is a meetup devoted to the research and development of Bitcoin'

menu:
  - {name: 'Events', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/Austin-Bitcoin-Developers/', external: true}
